
---
  - name: partition, garphical-target,crontab, haproxy
    hosts: projet
    gather_facts: yes
    become: yes
    vars_files:
            # - /home/ansible/projet/index.html.j2
    vars:
      haproxy_backend_servers:
        - name: formation
          address: 172.19.10.79:80
        - name: ansible_projet
          address: 172.19.10.166:80
    roles:
      - geerlingguy.haproxy

    tasks:
      - name: télécharger httpd la dernière version de apache
        yum:
          name: httpd
          state: latest
      - name: installer httpd
        yum:
          name: httpd
          state: present
     
      - name: redémarrer du service httpd
        service:
          name: httpd
          state: restarted
      - name: changer le default target en graphical target
        file:
          dest: /etc/systemd/system/default.target
          src: /usr/lib/systemd/graphical.target
          state: link
          force: yes
          owner: root
          group: root
      - name: mise à jour automatique de des paquets la  machine test tous les jours
        cron:
          name: mise à jour des paquets
          minute: '0'
          hour: '1'
          job: sudo apt update
          user: ansible
         
